spring:
  profile.active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/foro_hub
    username: root
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-stacktrace: never
api:
  security:
    secret: ${JWT_SECRET:123456}
